project_id: '478619'
preserve_hierarchy: true
api_token_env: "CROWDIN_PERSONAL_TOKEN"
files: [
    # JSON translation files
    {
      source: '/i18n/en/**/*',
      translation: '/i18n/%two_letters_code%/**/%original_file_name%',
    },
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
    },
  ]