#!/usr/bin/env python3
import json
import subprocess
import csv
import io
import sys
import os
from pathlib import Path
import tempfile
from typing import Optional
from urllib.request import urlretrieve

API_KEY = os.getenv("TENDERLY_API_KEY")
if API_KEY is None:
    print("Please set the TENDERLY_API_KEY environment variable.")
    sys.exit(1)

ZERO_ADDRESS = f"0x{'0'*40}"
ZERO_BYTES32 = f"0x{'0'*64}"
PROXY_SLOT = "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc"

# Fee currencies that are stablecoins but are not issued by Mento. Anything else on the
# allowlist that is not a `Mento *` token — WETH and XAUt0, for example — is a fee
# currency but not a stablecoin, so it stays off the stablecoin page.
NON_MENTO_STABLECOIN_SYMBOLS = {"USDC", "USD₮", "USA₮"}

# The Mento stablecoins we expect to find on the allowlist. Membership is detected by the
# `Mento *` token name, so this set exists purely to make drift loud: if a token is
# renamed upstream it would otherwise vanish from the stablecoin page in silence.
EXPECTED_MENTO_SYMBOLS = {
    "AUDm", "BRLm", "CADm", "CHFm", "COPm", "EURm", "GBPm", "GHSm",
    "JPYm", "KESm", "NGNm", "PHPm", "USDm", "XOFm", "ZARm",
}

NETWORKS = {
    "mainnet": {
        "display_name": "Celo Mainnet",
        "files": {
            "rollup.json": "https://storage.googleapis.com/cel2-rollup-files/celo/rollup.json",
            "config.json": "https://storage.googleapis.com/cel2-rollup-files/celo/config.json",
            "deployment-l1.json": "https://storage.googleapis.com/cel2-rollup-files/celo/deployment-l1.json",
            "contracts-l1.json": "https://storage.googleapis.com/cel2-rollup-files/celo/contracts-l1.json",
        },
        "l2_rpc": "https://forno.celo.org",
        "fee_currency_directory": "0x15F344b9E6c3Cb6F0376A36A64928b13F62C6276",
        "l1_rpc": f"https://mainnet.gateway.tenderly.co/{API_KEY}",
        "l1_explorer": "https://eth.blockscout.com",
        "l2_explorer": "https://celo.blockscout.com",
    },
    "celo-sepolia": {
        "display_name": "Celo Sepolia Testnet",
        "files": {
            "rollup.json": "https://storage.googleapis.com/cel2-rollup-files/celo-sepolia/rollup.json",
            "deployment-l1.json": "https://storage.googleapis.com/cel2-rollup-files/celo-sepolia/deployment-l1.json",
            "contracts-l1.json": "https://storage.googleapis.com/cel2-rollup-files/celo-sepolia/contracts-l1.json",
        },
        "l2_rpc": "https://forno.celo-sepolia.celo-testnet.org",
        "fee_currency_directory": "0x9212Fb72ae65367A7c887eC4Ad9bE310BAC611BF",
        "l1_rpc": f"https://sepolia.gateway.tenderly.co/{API_KEY}",
        "l1_explorer": "https://eth-sepolia.blockscout.com",
        "l2_explorer": "https://celo-sepolia.blockscout.com",
    },
}

PAGE_HEADER_CORE_CONTRACTS = """
---
title: Core Contracts
id: core-contracts
---

[comment]: <> (DO NOT EDIT THIS FILE MANUALLY)
[comment]: <> (Autogenerated by `scripts/update_contracts.py`)

Core contract addresses for the Celo networks.
""".strip()

PAGE_HEADER_L1_CONTRACTS = """
---
title: L1 Contracts
id: l1-contracts
---

[comment]: <> (DO NOT EDIT THIS FILE MANUALLY)
[comment]: <> (Autogenerated by `scripts/update_contracts.py`)

L1 contract addresses for the Celo networks.
""".strip()

PAGE_HEADER_FEE_CURRENCIES = """
---
title: Fee Currencies
id: fee-currencies
og:description: Tokens allowlisted to pay gas fees on Celo Mainnet and the Celo Sepolia Testnet
---

[comment]: <> (DO NOT EDIT THIS FILE MANUALLY)
[comment]: <> (Autogenerated by `scripts/update_contracts.py`)

Celo lets you pay gas fees in ERC20 tokens instead of CELO. The tables below list the tokens currently on the governable on-chain allowlist, read from the `FeeCurrencyDirectory` core contract. See [Fee Abstraction](/build-on-celo/fee-abstraction/overview) for how this works.

<Note>
This is not a list of every token on Celo. For stablecoin addresses, see [Stablecoin Contracts](/tooling/contracts/stablecoin-contracts). For an overview of Celo's stablecoin ecosystem, see [Build with Local Stablecoins](/build-on-celo/build-with-local-stablecoin).
</Note>

Pass the **feeCurrency address** as the `feeCurrency` field on a transaction, and use the **token address** when transferring the token itself. The two differ for tokens that do not use 18 decimals — such as USDC, USD₮ and USA₮ — which are allowlisted through an adapter. See [Adapters for Non-18-Decimal Tokens](/build-on-celo/fee-abstraction/using-fee-abstraction#adapters-for-non-18-decimal-tokens).

<Tip>
You can also query the list of allowlisted fee currencies with the Celo CLI:

```sh
celocli network:whitelist
```
</Tip>

---
""".strip()

PAGE_HEADER_STABLECOIN_CONTRACTS = """
---
title: Stablecoin Contracts
id: stablecoin-contracts
og:description: Contract addresses for stablecoins on Celo Mainnet and the Celo Sepolia Testnet
---

[comment]: <> (DO NOT EDIT THIS FILE MANUALLY)
[comment]: <> (Autogenerated by `scripts/update_contracts.py`)

Contract addresses for stablecoins on Celo Mainnet and the Celo Sepolia Testnet. For an overview of the ecosystem these assets belong to, see [Build with Local Stablecoins](/build-on-celo/build-with-local-stablecoin). To find out which of them can also pay gas fees, see [Fee Currencies](/tooling/contracts/fee-currencies).

<Note>
These addresses are listed for convenience and do not imply any endorsement of the issuer or the asset. Verify an address against a block explorer before using it in production.
</Note>
""".strip()


def check_celocli_exists() -> bool:
    """Check if the celocli binary exists in PATH using only stdlib."""
    paths = os.environ.get("PATH", "").split(os.pathsep)
    exts = [""] + (
        os.environ.get("PATHEXT", "").split(os.pathsep) if os.name == "nt" else []
    )
    for path in paths:
        for ext in exts:
            full_path = os.path.join(path, "celocli" + ext)
            if os.path.isfile(full_path) and os.access(full_path, os.X_OK):
                return True
    return False


def fetch_celo_cli_csv(network: str, command: str) -> str:
    """Run celocli and return its CSV output."""
    try:
        result = subprocess.run(
            [
                "celocli",
                command,
                "--node",
                NETWORKS[network]["l2_rpc"],
                "--csv",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        sys.exit(f"Error: celocli failed:\n{e.stderr}")
    except FileNotFoundError:
        sys.exit("Error: celocli binary not found in PATH.")


def csv_to_markdown(csv_text: str, network: str) -> str:
    """Convert CSV text to Markdown table with proxy links."""
    reader = csv.DictReader(io.StringIO(csv_text))
    lines = ["| Contract | Proxy |", "| -------- | ------ |"]
    for row in reader:
        contract = row.get("Contract", "").strip()
        proxy = row.get("Proxy", "").strip()
        if proxy:
            link = f"[`{proxy}`]({NETWORKS[network]['l2_explorer']}/address/{proxy})"
            lines.append(f"| {contract} | {link} |")
    return "\n".join(lines)


def cast_call(address: str, signature: str, rpc: str) -> Optional[str]:
    """Read a contract via `cast call`. Returns None when the call reverts."""
    result = subprocess.run(
        ["cast", "call", address, signature, "--rpc-url", rpc],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip().strip('"') or None


def get_fee_currencies(network: str, overrides: dict) -> list:
    """Read the fee-currency allowlist from FeeCurrencyDirectory.

    Each allowlisted entry is either the token itself or an adapter wrapping it.
    Adapters exist for tokens that do not use 18 decimals, because gas is always priced
    in 18 decimals. Two adapter generations are deployed and they expose the underlying
    token under different names, so try both.
    """
    net = NETWORKS[network]
    rpc = net["l2_rpc"]

    raw = cast_call(net["fee_currency_directory"], "getCurrencies()(address[])", rpc)
    if not raw:
        sys.exit(f"Error: could not read the fee currency allowlist for {network}.")

    rows = []
    for fee_currency in [a.strip() for a in raw.strip("[]").split(",")]:
        token = (
            cast_call(fee_currency, "adaptedToken()(address)", rpc)
            or cast_call(fee_currency, "getAdaptedToken()(address)", rpc)
            or fee_currency
        )
        symbol = cast_call(token, "symbol()(string)", rpc) or ""
        rows.append(
            {
                "name": cast_call(token, "name()(string)", rpc) or "",
                "symbol": overrides.get(symbol, symbol),
                "fee_currency": fee_currency,
                "token": token,
            }
        )

    missing = EXPECTED_MENTO_SYMBOLS - {r["symbol"] for r in rows}
    if network == "mainnet" and missing:
        print(
            f"  ! expected Mento stablecoins missing from the allowlist: "
            f"{', '.join(sorted(missing))}. If they were renamed upstream, update "
            f"EXPECTED_MENTO_SYMBOLS and the `Mento ` name check."
        )

    return sorted(rows, key=lambda r: r["symbol"].lower())


def fee_currencies_to_markdown(rows: list, network: str) -> str:
    lines = [
        "| Token | Symbol | feeCurrency Address | Token Address |",
        "| ----- | ------ | ------------------- | ------------- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['name']} | {row['symbol']} "
            f"| {explorer_link(row['fee_currency'], network)} "
            f"| {explorer_link(row['token'], network)} |"
        )
    return "\n".join(lines)


def explorer_link(address: str, network: str) -> str:
    """Render an address as a Markdown link to that network's L2 explorer."""
    if not address:
        return "-"
    return f"[`{address}`]({NETWORKS[network]['l2_explorer']}/address/{address})"


def load_stablecoin_data() -> dict:
    """Load curated stablecoin metadata that has no on-chain registry to read from."""
    with Path("scripts/data/stablecoins.json").open() as f:
        return json.load(f)


def stablecoins_to_markdown(rows_by_network: dict, data: dict) -> str:
    """Build one stablecoin table spanning both networks.

    Mento tokens plus the non-Mento stablecoins come from the fee-currency allowlist,
    which is the only source that covers Celo Sepolia. Third-party issuers have no
    registry to read, so they are curated in scripts/data/stablecoins.json.
    """
    issuers = data["issuers"]

    def allowlisted_stablecoins(rows: list, network: str) -> dict:
        """Map symbol -> token address, keeping only stablecoins."""
        found = {}
        for row in rows:
            symbol, name = row["symbol"], row["name"]
            if not (name.startswith("Mento ") or symbol in NON_MENTO_STABLECOIN_SYMBOLS):
                continue
            if symbol in found and found[symbol] != row["token"]:
                print(
                    f"  ! {symbol} resolves to two addresses on {network} "
                    f"({found[symbol]} and {row['token']}); the table will show the "
                    f"last one. Disambiguate them before publishing."
                )
            found[symbol] = row["token"]
        return found

    mainnet = allowlisted_stablecoins(rows_by_network["mainnet"], "mainnet")
    sepolia = allowlisted_stablecoins(rows_by_network["celo-sepolia"], "celo-sepolia")

    lines = [
        "| Stablecoin | Issuer | Celo Mainnet | Celo Sepolia Testnet |",
        "| ---------- | ------ | ------------ | -------------------- |",
    ]

    for symbol in sorted(mainnet, key=str.lower):
        issuer = issuers.get(symbol, issuers["_default"])
        lines.append(
            f"| **{symbol}** | [{issuer['name']}]({issuer['url']}) "
            f"| {explorer_link(mainnet[symbol], 'mainnet')} "
            f"| {explorer_link(sepolia.get(symbol, ''), 'celo-sepolia')} |"
        )

    for token in sorted(data["third_party"], key=lambda t: t["symbol"].lower()):
        # Once a curated token is allowlisted as a fee currency it is already rendered
        # above, with testnet coverage the curated entry cannot provide.
        if token["symbol"] in mainnet:
            continue
        lines.append(
            f"| **{token['symbol']}** | [{token['issuer']}]({token['issuer_url']}) "
            f"| {explorer_link(token['mainnet_address'], 'mainnet')} "
            f"| {explorer_link(token.get('sepolia_address', ''), 'celo-sepolia')} |"
        )

    return "\n".join(lines)


def get_l1_contracts(network: str) -> str:
    net = NETWORKS[network]
    base_url = net["l1_explorer"]

    lines = ["| Contract | Address |", "| -------- | ------- |"]
    with tempfile.TemporaryDirectory() as tmpdir:
        tmppath = Path(tmpdir)
        for filename, url in net["files"].items():
            urlretrieve(url, tmppath / filename)

        l1 = json.load(open(tmppath / "contracts-l1.json"))

        for contract, address in l1.items():
            if address == ZERO_ADDRESS:
                continue

            print("L1:", contract)
            lines.append(f"| {contract} | [`{address}`]({base_url}/address/{address}) |")

            if contract.endswith("Proxy"):
                impl = retrieve_impl(contract, address, net)
                if impl is None:
                    print("  No implementation found!")
                    continue

                print("  Impl:", impl)
                lines.append(f"| {contract.replace('Proxy', 'Impl')} | [`{impl}`]({base_url}/address/{impl}) |")

    return "\n".join(lines)

def bytes32_to_address(b: str) -> str:
    if len(b) != 66 or not b.startswith("0x"):
        raise ValueError(f"Invalid bytes32: {b}")
    return f"0x{b[26:]}"

def resolve_delegate_proxy(contract, address, net) -> Optional[str]:
    # compute storage slot for address manager
    manager_slot = subprocess.check_output(
        [
            "cast",
            "index",
            "address",
            address,
            "1",
        ],
        encoding="utf-8",
    ).strip()

    # load address manager address from storage
    manager_address = subprocess.check_output(
        [
            "cast",
            "storage",
            "-r",
            net["l1_rpc"],
            address,
            manager_slot,
        ],
        encoding="utf-8",
    ).strip()

    # if no address manager, return
    if manager_address == ZERO_BYTES32:
        return None

    manager_address = bytes32_to_address(manager_address)

    # retrieve implementation address from address manager
    impl = subprocess.check_output(
        [
            "cast",
            "call",
            "-r",
            net["l1_rpc"],
            manager_address,
            "getAddress(string)(address)",
            f'OVM_{contract.replace("Proxy", "")}',
        ],
        encoding="utf-8",
    ).strip()

    return impl

def retrieve_impl(contract, address, net) -> tuple[bool, str]:
    impl = subprocess.check_output(
        [
            "cast",
            "storage",
            "-r",
            net["l1_rpc"],
            address,
            PROXY_SLOT,
        ],
        encoding="utf-8",
    ).strip()

    if impl == ZERO_BYTES32:
        return resolve_delegate_proxy(contract, address, net)

    impl = bytes32_to_address(impl)

    return impl

def main():
    if not check_celocli_exists():
        sys.exit(
            "Error: 'celocli' binary not found. Please install it first: npm install -g @celo/celocli"
        )

    print("Fetching core contract data from celocli...")
    with Path("tooling/contracts/core-contracts.mdx").open("w") as f:
        f.write(PAGE_HEADER_CORE_CONTRACTS)

        for network, data in NETWORKS.items():
            print(f"> Fetching contract data from celocli for {network}...")

            csv_output = fetch_celo_cli_csv(network, "network:contracts")
            markdown = csv_to_markdown(csv_output, network)

            f.write(f"\n\n## {data['display_name']}\n\n")
            f.write(markdown)

    # Read every input before opening an output file. Opening for write truncates it, so
    # a late failure here would otherwise leave a published page as a bare header.
    stablecoin_data = load_stablecoin_data()
    symbol_overrides = {
        k: v for k, v in stablecoin_data["symbol_overrides"].items()
        if not k.startswith("_")
    }

    print("Reading the fee currency allowlist from FeeCurrencyDirectory...")
    fee_currencies = {}
    for network in NETWORKS:
        print(f"> Reading fee currencies for {network}...")
        fee_currencies[network] = get_fee_currencies(network, symbol_overrides)

    with Path("tooling/contracts/fee-currencies.mdx").open("w") as f:
        f.write(PAGE_HEADER_FEE_CURRENCIES)

        for network, data in NETWORKS.items():
            f.write(f"\n\n## {data['display_name']}\n\n")
            f.write(fee_currencies_to_markdown(fee_currencies[network], network))

    print("Building stablecoin contract page...")
    with Path("tooling/contracts/stablecoin-contracts.mdx").open("w") as f:
        f.write(PAGE_HEADER_STABLECOIN_CONTRACTS)
        f.write("\n\n")
        f.write(stablecoins_to_markdown(fee_currencies, stablecoin_data))

    print("Fetching L1 contract data...")
    with Path("tooling/contracts/l1-contracts.mdx").open("w") as f:
        f.write(PAGE_HEADER_L1_CONTRACTS)

        for network, data in NETWORKS.items():
            print(
                f"> Fetching l1 contract data for {network}..."
            )

            markdown = get_l1_contracts(network)

            f.write(f"\n\n## {data['display_name']}\n\n")
            f.write(markdown)


if __name__ == "__main__":
    main()
