
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#if !defined (__SECRET_INSIDE_HEADER__) && !defined (SECRET_COMPILATION)
#error "Only <secret/secret.h> can be included directly."
#endif

#ifndef __SECRET_ENUM_TYPES_H__
#define __SECRET_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "libsecret/secret-collection.h" */
GType secret_collection_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_COLLECTION_FLAGS (secret_collection_flags_get_type ())
GType secret_collection_create_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_COLLECTION_CREATE_FLAGS (secret_collection_create_flags_get_type ())

/* enumerations from "libsecret/secret-item.h" */
GType secret_item_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_ITEM_FLAGS (secret_item_flags_get_type ())
GType secret_item_create_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_ITEM_CREATE_FLAGS (secret_item_create_flags_get_type ())

/* enumerations from "libsecret/secret-schema.h" */
GType secret_schema_attribute_type_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_SCHEMA_ATTRIBUTE_TYPE (secret_schema_attribute_type_get_type ())
GType secret_schema_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_SCHEMA_FLAGS (secret_schema_flags_get_type ())

/* enumerations from "libsecret/secret-schemas.h" */
GType secret_schema_type_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_SCHEMA_TYPE (secret_schema_type_get_type ())

/* enumerations from "libsecret/secret-service.h" */
GType secret_service_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_SERVICE_FLAGS (secret_service_flags_get_type ())
GType secret_search_flags_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_SEARCH_FLAGS (secret_search_flags_get_type ())

/* enumerations from "libsecret/secret-types.h" */
GType secret_error_get_type (void) G_GNUC_CONST;
#define SECRET_TYPE_ERROR (secret_error_get_type ())
G_END_DECLS

#endif /* __SECRET_ENUM_TYPES_H__ */

/* Generated data ends here */

